/* Banco PL-300 · ExamTopics (Examtopics_bd) · bloque 3 */
var EXAM = window.EXAM || (window.EXAM = []);
(function(){
var S = "ExamTopics · Preguntas";
EXAM.push(
{k:"Visualización", t:"interactividad", s:S, q:"Primera página con dos vistas (ventas por código postal con mapa y ventas por mes), ambas con un segmentador de Chain. Se alterna con botones y la selección de Chain debe mantenerse. ¿Mínimo de marcadores y qué propiedad?", a:"Dos marcadores (uno por vista) con la propiedad Display (Mostrar) activada y Datos desactivada, para que el marcador cambie la visibilidad de los visuales pero no el estado del segmentador."},
{k:"Visualización", t:"interactividad", s:S, q:"Informe de cuatro páginas con segmentadores de los mismos cuatro campos en cada una; seleccionar en una página no afecta a las demás. ¿Dos soluciones posibles?", a:"Sincronizar los segmentadores entre páginas, o sustituirlos por filtros de nivel de informe (todas las páginas)."},
{k:"Service", t:"service", s:S, q:"Usuarios externos ven un panel; gerentes, panel e informe de gerentes; empleados, panel e informe con RLS. Todos deben poder etiquetar a los administradores si ven un problema en el panel y que los demás lo vean. ¿Qué usas?", a:"Comentarios (con @menciones) en el panel. Teams, alertas o suscripciones no cumplen la visibilidad para todos."},
{k:"Service", t:"interactividad", s:S, q:"report1 usa un modelo compartido. Minimiza el riesgo de exfiltración de datos de report1 sin afectar a otros informes.", a:"En la configuración de report1, elegir «No permitir que los usuarios finales exporten ningún dato». RLS o cambiar permisos del modelo afectarían a los demás informes."},
{k:"Modelado", t:"grupos", s:S, q:"Usuarios móviles; el informe debe mostrar datos según la ubicación de cada usuario. ¿Qué dos acciones?", a:"Establecer la categoría de datos geográfica (ciudad, país…) en las columnas relevantes y usar esas columnas geográficas en los visuales; así Power BI Mobile puede filtrar por la ubicación."},
{k:"Power Query", t:"vertipaq", s:S, q:"Consulta Sales: solo se usa la parte de fecha de Sales_Date y solo filas con estado Finished. Reduce el tiempo de carga sin afectar al análisis. ¿Qué dos acciones?", a:"Eliminar las filas con Status = Canceled y dividir Sales_Date en columnas separadas de fecha y hora (menor cardinalidad). Según el apunte; algunas soluciones prefieren eliminar Canceled Date, que no se usa tras filtrar."},
{k:"Power Query", t:"combinar", s:S, q:"Excel con Table1 (Sheet1) y Table2 (Sheet2); necesitas una tabla de productos de una columna sin duplicados. ¿Tres acciones, en orden?", a:"1) Importar desde Excel seleccionando Table1 y Table2. 2) En Power Query, anexar Table2 a Table1. 3) Seleccionar Table1 y Quitar duplicados."},
{k:"Seguridad", t:"rls", s:S, q:"Dos tablas con RLS; al relacionarlas, el filtro cruzado bidireccional debe respetar la RLS. ¿Qué haces?", a:"Crear una relación activa y marcar «Aplicar filtro de seguridad en ambas direcciones». Integridad referencial o relaciones inactivas no resuelven."},
{k:"Seguridad", t:"rls", s:S, q:"Role1 filtra City[State Province] = \"Kentucky\" y Role2 filtra Date[Calendar Year] = 2020. Un usuario pertenece a ambos roles. ¿Qué ve?", a:"Las filas donde State Province es Kentucky O Calendar Year es 2020: los roles se combinan con OR (unión de permisos)."},
{k:"Visualización", t:"interactividad", s:S, q:"En una página con un mapa y otros visuales: ¿qué efecto tiene seleccionar en un visual con interacción «ninguno» y en uno con la interacción por defecto?", a:"Según la configuración del ejemplo: un visual no se ve afectado (interacción Ninguno) y el otro aplica filtro cruzado (resalta). Lee bien qué visual es el origen y cuál el destino."},
{k:"Service", t:"roles", s:S, q:"Informes de RR. HH. con RLS; cada gerente de RR. HH. solo debe interactuar con los datos de su región y no debe poder cambiar el diseño. ¿Cómo das acceso?", a:"Publicar los informes en una aplicación y dar acceso a los gerentes. Como miembros del área podrían editar y no les aplicaría la RLS."},
{k:"Service", t:"roles", s:S, q:"Workspace1 contiene DS1 y RPT1. Un usuario quiere crear un informe con DS1 y publicarlo en otra área, con los mínimos permisos.", a:"Darle permiso de Compilación (Build) sobre DS1."},
{k:"Service", t:"service", s:S, q:"Panel con una tarjeta de ventas del año; los usuarios son Visores. Un usuario quiere recibir a diario el número de la tarjeta. ¿Qué haces?", a:"Crear una suscripción (correo periódico). Una alerta solo avisa al superar un umbral."},
{k:"Service", t:"roles", s:S, q:"Un usuario debe poder agregar miembros a un área de trabajo con privilegio mínimo. ¿Qué rol?", a:"Miembro (puede añadir miembros, colaboradores y visores). Administrador sería más de lo necesario."},
{k:"Rendimiento", t:"vertipaq", s:S, q:"PBIX de 550 MB en capacidad compartida, tabla de hechos de 12 M filas, actualización dos veces al día, una sola página con 15 visuales personalizados y 10 predeterminados; tarda mucho en cargar. ¿Qué recomiendas?", a:"Repartir los visuales en varias páginas: cada visual lanza sus consultas al cargar la página. RLS, más visuales personalizados o más actualizaciones no ayudan."},
{k:"Orígenes", t:"obtener", s:S, q:"Aplicación de gestión de proyectos hecha con Power Apps y alojada en Teams. ¿Qué conector usas?", a:"Dataverse (donde Power Apps guarda los datos)."},
{k:"Service", t:"service", s:S, q:"Tienes más de 100 modelos y 10 verificados con los estándares de calidad deben aparecer arriba en las búsquedas. ¿Qué haces?", a:"Certificarlos. Promover también los destaca, pero la certificación indica cumplimiento de estándares corporativos y los coloca primero."},
{k:"Visualización", t:"percepcion", s:S, q:"Visual para RR. HH. con el número histórico de empleados y la previsión de los próximos seis meses.", a:"Gráfico de líneas con previsión (panel Análisis &gt; Previsión)."},
{k:"Visualización", t:"percepcion", s:S, q:"Configura un visual de influenciadores clave como el de la imagen (Ventas totales explicadas por ocupación y ampliadas por ciudad).", a:"Analizar: Total Sales. Explicar por: Occupation. Expandir por: City."},
{k:"Visualización", t:"percepcion", s:S, q:"Visual que compare ingresos y costes a lo largo del tiempo.", a:"Gráfico de líneas (cascada, área apilada o anillo no comparan bien dos series en el tiempo)."},
{k:"Visualización", t:"percepcion", s:S, q:"Identificar segmentos de clientes dinámicamente según la tasa de rebote por fuente, geografía y demografía con el mínimo esfuerzo de análisis.", a:"Influenciadores clave (pestaña Segmentos principales)."},
{k:"Visualización", t:"percepcion", s:S, q:"Influenciadores clave sobre la cantidad por pedido devuelve, entre otros, «País del cliente = Austria: 18,8». ¿Qué afirmación es correcta?", a:"Los clientes de Austria piden 18,8 unidades más que la cantidad media por pedido."},
{k:"Visualización", t:"interactividad", s:S, q:"Barras: clientes por segmento; columnas: ventas por mes. Al seleccionar un segmento debes ver qué parte de las ventas de cada mes es de ese segmento. ¿Interacción del gráfico de columnas?", a:"Resaltar: muestra la parte del segmento sobre el total del mes."},
{k:"Power Query", t:"combinar", s:S, q:"Dos Azure SQL con las mismas tablas; una consulta Customers en cada una. Combínalas en una tabla minimizando el tamaño del modelo y admitiendo actualización programada.", a:"Anexar como consulta nueva y deshabilitar la carga de las dos consultas originales (para no duplicar datos en el modelo)."},
{k:"Modelado", t:"obtener", s:S, q:"Modelo con Customer (diaria), Date (cada tres años), Sales (casi tiempo real) y SalesAggregate (semanal). Minimiza el tiempo de carga de visuales cumpliendo la actualización. ¿Modo de cada tabla?", a:"Sales: DirectQuery (casi tiempo real). SalesAggregate: Importar. Customer y Date: Dual (se relacionan con Sales en DirectQuery y con la tabla importada, así sirven a ambas sin consultas mixtas lentas)."},
{k:"Power Query", t:"vertipaq", s:S, q:"Conector personalizado con ID, De, A, Asunto, Cuerpo y Tiene adjuntos de más de 10 M correos; analizas a quién se escribe. Impide leer los correos y minimiza el modelo.", a:"Eliminar Asunto y Cuerpo durante la importación. Ocultarlas o usar RLS no reduce el tamaño ni impide del todo el acceso."},
{k:"Service", t:"service", s:S, q:"Publicas el modelo en powerbi.com (orígenes en la nube). ¿Necesitas puerta de enlace? ¿Necesitas actualización programada? ¿Puedes usar autenticación básica?", a:"Puerta de enlace: no. Actualización programada: no (en el escenario). Autenticación básica: sí."},
{k:"Orígenes", t:"obtener", s:S, q:"Debes obtener datos de tablas de SQL Server. ¿Cómo configuras la conexión?", a:"DirectQuery con credenciales de base de datos (según el escenario del examen)."},
{k:"Service", t:"service", s:S, q:"Panel creado desde un informe que importa de SQL Server. ¿Qué ocurrió a la hora indicada en el icono (12:03:06)?", a:"Se actualizó la caché de los iconos del panel (el panel actualiza su caché periódicamente)."},
{k:"Service", t:"dataflows", s:S, q:"Excel en un servidor de archivos importado en un informe publicado; los datos deben actualizarse cada cuatro horas. ¿Qué haces primero?", a:"Implementar una puerta de enlace de datos local (el archivo está en un servidor de la red interna)."},
{k:"Visualización", t:"percepcion", s:S, q:"Tarjeta: valores &gt;= 100 con fuente rojo oscuro y &lt; 100 gris oscuro, con el mínimo esfuerzo. ¿Qué formato condicional?", a:"Reglas."},
{k:"Visualización", t:"percepcion", s:S, q:"El color del indicador de Ventas totales debe basarse en el % de crecimiento interanual, usando solo cálculos existentes. ¿Cómo lo configuras?", a:"Formato condicional de color de fondo (Background color) por reglas sobre la medida de % de crecimiento."},
{k:"Power Query", t:"transformar", s:S, q:"Excel de ingresos con productos y departamentos en filas y años en columnas; necesitas visuales por año y producto con columnas bien nombradas. ¿Tres acciones, en orden?", a:"1) Usar la primera fila como encabezado. 2) Seleccionar Departamento y Producto y anular la dinamización de las otras columnas. 3) Renombrar Atributo como Año y Valor como Revenue."},
{k:"Service", t:"service", s:S, q:"Construyes un panel que se verá en vertical en móviles a partir de informes existentes. ¿Cuatro acciones, en orden?", a:"1) Anclar elementos del informe al panel. 2) Abrir el panel. 3) Cambiar a la vista de teléfono. 4) Reorganizar y redimensionar los visuales."},
{k:"Service", t:"roles", s:S, q:"Asigna con privilegio mínimo: un usuario que debe poder compartir contenido y añadir colaboradores, y otro que debe publicar y editar contenido.", a:"Usuario 1: Miembro. Usuario 2: Colaborador."}
);
})();
