/* Banco PL-300 · ExamTopics (Examtopics_bd) · bloque 2 */
var EXAM = window.EXAM || (window.EXAM = []);
(function(){
var S = "ExamTopics · Preguntas";
EXAM.push(
{k:"Power Query", t:"obtener", s:S, q:"Un PBIX importa tablas de una base de datos Azure SQL que se migrará a otra base de datos Azure SQL. ¿Cómo cambias las conexiones con el mínimo esfuerzo?", a:"Modificar la configuración del origen de datos (Configuración de origen de datos &gt; Cambiar origen): cambia todas las consultas que apuntan a ese origen a la vez. Editar cada consulta, crear consultas nuevas o pasar por un PBIT supone más trabajo."},
{k:"Visualización", t:"interactividad", s:S, q:"Un informe muestra gastos por mes en un gráfico de líneas y los usuarios deben poder elegir verlo como líneas o columnas, con mínimo desarrollo y mantenimiento.", a:"Añadir un gráfico de columnas, marcadores y un botón (navegador de marcadores) para alternar entre los dos visuales. Un informe móvil o una página aparte duplican el mantenimiento."},
{k:"Orígenes", t:"service", s:S, q:"Publicaste un informe con un modelo que importa un Excel de SharePoint y contiene varias medidas. Necesitas crear otro informe con esos datos con el mínimo esfuerzo. ¿Qué origen usas?", a:"El modelo semántico (conjunto de datos) de Power BI ya publicado: reutiliza las medidas y el trabajo de preparación."},
{k:"Service", t:"interactividad", s:S, q:"Los usuarios deben poder exportar los datos resumidos de los visuales pero no los datos subyacentes. ¿Qué haces?", a:"Según el apunte, configurar en Power BI Service los permisos del modelo. Ten presente que la opción de exportación (solo resumidos / resumidos y subyacentes / ninguno) se define en Desktop en Opciones &gt; Archivo actual &gt; Configuración de informe, y también por informe en Service; muchas soluciones señalan esa opción del archivo actual."},
{k:"Visualización", t:"percepcion", s:S, q:"Necesitas un visual que muestre tendencias y otra información útil automáticamente y que se actualice con las selecciones de otros visuales. ¿Cuál?", a:"Según el apunte, árbol de descomposición. Revisa también la narrativa inteligente: genera texto automático con tendencias y se actualiza con los filtros, y es la respuesta que defiende buena parte de la comunidad."},
{k:"Service", t:"percepcion", s:S, q:"ReportA usa un tema personalizado y DashboardA debe usar ese tema con el mínimo esfuerzo. ¿Qué dos acciones?", a:"Publicar ReportA en Power BI (guardando el tema JSON) y, desde DashboardA, cargar ese tema JSON personalizado."},
{k:"Seguridad", t:"rls", s:S, q:"Informe de ventas del último año por región con acceso por región mediante roles. ¿Qué cuatro acciones, en orden?", a:"1) Importar los datos en Power BI Desktop. 2) En Administrar roles, Crear (rol con filtro DAX). 3) Publicar el informe. 4) Asignar usuarios al rol en Service. (El apunte lista asignar antes de publicar, pero la asignación se hace en Service tras publicar.)"},
{k:"Orígenes", t:"obtener", s:S, q:"Tabla Order de SQL Server con más de 100 millones de filas; en desarrollo necesitas importar solo una muestra. ¿Sirve añadir una cláusula WHERE a la instrucción SQL? ¿Y un FILTER en DAX? ¿Y un filtro de nivel de informe?", a:"WHERE en la instrucción SQL: sí (filtra en el origen). FILTER en DAX: no (los datos ya se han importado). Filtro de nivel de informe: no (también actúa después de importar)."},
{k:"Visualización", t:"percepcion", s:S, q:"Gráfico de barras con Salario por Empleado. Debes mostrar qué empleados están por encima del salario mediano. ¿Sirve una línea de promedio, una de percentil al 50 %, una de mediana o una constante de 0,5?", a:"Percentil al 50 %: sí. Mediana: sí. Promedio: no (la media no es la mediana). Constante 0,5: no."},
{k:"Service", t:"roles", s:S, q:"Debes dar acceso de solo lectura a toda la organización a un panel y varios informes de un área. ¿Sirve compartir cada elemento con un grupo de Azure AD con todos? ¿Publicar una app para toda la organización? ¿Marcar «Incluido en la aplicación»?", a:"Publicar una aplicación para toda la organización: sí. Compartir elemento a elemento con un grupo: no (según el apunte). Solo marcar «Incluido en la aplicación»: no, falta publicar la app."},
{k:"Service", t:"roles", s:S, q:"Un usuario debe poder crear un panel con visuales de los informes de un área de trabajo. ¿Qué haces?", a:"Agregarlo como Miembro del área de trabajo (los Visores no pueden crear contenido; compartir o dar lectura no basta)."},
{k:"Visualización", t:"percepcion", s:S, q:"Gráfico de dispersión de Coste total frente a Ventas totales. Debes mostrar cómo evoluciona esa relación a lo largo del tiempo.", a:"Añadir un eje de reproducción (Play axis) con el campo de fecha."},
{k:"DAX", t:"ti", s:S, q:"Balances tiene saldos diarios por cuenta activa (también el último día). Accounts = CALCULATE(DISTINCTCOUNT(Balances[AccountID]), LASTDATE('Date'[Date])). ¿Muestra a nivel de año las cuentas activas todo el año? ¿A nivel de mes las activas todo el mes? ¿A nivel de día las del día?", a:"Año: no. Mes: no. Día: sí. LASTDATE devuelve el último día del periodo, así que la medida cuenta las cuentas activas ese último día, no las activas durante todo el periodo."},
{k:"Visualización", t:"percepcion", s:S, q:"¿Cómo creas la línea horizontal punteada del percentil 40 de las ventas diarias del periodo?", a:"Desde el panel Análisis, añadir una línea de percentil con Total Sales y percentil 40 %. Una constante fija no se adapta al periodo."},
{k:"Power Query", t:"combinar", s:S, q:"Azure SQL erp1 con Orders, Order Line Items y Products. Analizas pedidos y valor en el tiempo y pedidos por atributos de producto, minimizando los tiempos de respuesta de los visuales. ¿Qué haces?", a:"En Power Query, combinar Order Line Items con Products (desnormalizar los atributos de producto en la tabla de hechos de líneas), menos relaciones y joins en las consultas."},
{k:"DAX", t:"calendario", s:S, q:"Tabla de fechas con 10 años naturales completos incluido el actual. ¿Cómo completas la expresión?", a:"Con CALENDAR, YEAR y TODAY: CALENDAR(DATE(YEAR(TODAY()) - 9, 1, 1), DATE(YEAR(TODAY()), 12, 31))."},
{k:"Seguridad", t:"rls", s:S, q:"Modelo con Country[Manager_Email]; cada gerente representa un país y solo debe ver ese país, con el mínimo de roles. ¿Qué dos acciones?", a:"Crear un único rol que filtre Country[Manager_Email] con USERNAME() (o USERPRINCIPALNAME) y, en la relación entre Purchase Detail y Purchase, activar «Aplicar filtro de seguridad en ambas direcciones» para que la seguridad llegue a la tabla de detalle."},
{k:"DAX", t:"calculate", s:S, q:"Medida que devuelva el porcentaje de ingresos por categoría de producto. ¿Cómo la completas?", a:"Con DIVIDE, CALCULATE y ALL: DIVIDE(SUM(Sales[Revenue]), CALCULATE(SUM(Sales[Revenue]), ALL('Product'[Category]))). ALL quita el filtro de categoría para obtener el total del denominador."},
{k:"Power Query", t:"transformar", s:S, q:"Excel financiero con las medidas en filas y los años en columnas. Debes soportar visuales de todas las medidas en el tiempo y cálculos interanuales. ¿Qué cuatro acciones, en orden?", a:"1) Transponer la tabla. 2) Anular la dinamización de otras columnas que no sean Measure. 3) Renombrar la columna de atributo (Medidas) como Año. 4) Cambiar el tipo de la columna Año a fecha."},
{k:"Modelado", t:"vertipaq", s:S, q:"Inventario de Productos (25 M filas) relacionado con Fecha por DateKey y con Producto por ProductKey; también tiene MovementDate. Reduce el tamaño sin perder información.", a:"Eliminar MovementDate: duplica la información de DateKey (que ya relaciona con Fecha) y es una columna de alta cardinalidad. Cambiar el resumen, convertir UnitCost a entero o borrar la relación no reducen sin perder información."},
{k:"Modelado", t:"vertipaq", s:S, q:"Modelo Orders cerca del límite de capacidad compartida; analiza ventas totales, recuento de pedidos y clientes nuevos y recurrentes. ¿Reduce el tamaño manteniendo el análisis: resumir Orders por CustomerID, OrderID y OrderDate; eliminar CustomerID; eliminar UnitPrice y Discount?", a:"Resumir por CustomerID, OrderID y OrderDate: sí. Eliminar CustomerID: no (hace falta para clientes nuevos/recurrentes). Eliminar UnitPrice y Discount: el apunte duda; la mayoría responde sí si las ventas ya están precalculadas en otra columna (por ejemplo SalesAmount) y no se usan en el análisis."},
{k:"Modelado", t:"relaciones", s:S, q:"Products se relaciona con ProductCategory por ProductCategoryID y debes analizar ventas por categoría. ¿Cardinalidad y dirección?", a:"Uno a varios (de ProductCategory a Products) con dirección de filtro cruzado única."},
{k:"Modelado", t:"relaciones", s:S, q:"Base de datos con Customer y Transaction. ¿Qué relación usas?", a:"Uno a varios de Customer a Transaction."},
{k:"Perfil de datos", t:"perfilado", s:S, q:"Con las estadísticas y la distribución de column1: ¿cuántos valores aparecen solo una vez? ¿Pear, Flowering aparece más que cuál?", a:"Hay 20 valores que aparecen solo una vez (los únicos). Pear, Flowering aparece con más frecuencia que Ash, Green (se lee en las barras de distribución)."},
{k:"Power Query", t:"combinar", s:S, q:"Tablas Customer y Address de Excel (Customer ID y Address ID únicos). Necesitas una fila por cliente con Ciudad, Estado/Región y País.", a:"Combinar (merge) Customer y Address por Address ID. Anexar las apilaría; agrupar o transponer no sirven."},
{k:"Modelado", t:"vertipaq", s:S, q:"Tabla Impresiones con ~30 M filas al mes. Necesitas recuentos de impresiones por día, campaña y Site_name del último año minimizando el tamaño del modelo. ¿Qué dos acciones?", a:"Agrupar las impresiones por Ad_id, Site_name e Impression_date agregando con recuento de filas (en Power Query) y crear relaciones uno a varios entre las tablas."}
);
})();
