/* Banco PL-300 · ExamTopics: casos de estudio (Litware, Contoso x2) y primeras preguntas de Examtopics_bd */
var EXAM = window.EXAM || (window.EXAM = []);
var NOTES = window.NOTES || (window.NOTES = []);
(function(){
var C1 = "ExamTopics · Caso 1: Litware (tienda online)";
var C2 = "ExamTopics · Caso 2: Contoso (actividades al aire libre)";
var C3 = "ExamTopics · Caso 3: Contoso (empresa de deportes)";
var S = "ExamTopics · Preguntas";

NOTES.push(
{t:"pl300", s:C1, h:`
<p><b>Litware, Inc.</b>: minorista online con paneles e informes de Power BI; datos de SQL Server, Excel, texto y otros; autentica con Azure AD.</p>
<p>Tabla Date: <code>dateid</code> en formato yyyymmdd, <code>month</code> en yyyymm, <code>week</code> y <code>Weekly_Returns[weekid]</code> en yyyyww. Cada Regionid la gestiona un único gerente de ventas. Preocupa la calidad: se quieren detectar importes de venta negativos.</p>
<p><b>Requisitos:</b> visual de ventas por región para ejecutivos; ventas y devoluciones semanales para gerentes regionales; cada gerente de ventas solo ve su región; visual de desempeño frente a objetivos; informes con el número de transacciones; mes con formato «Feb 2020»; visual filtrable de forma independiente por mes de venta y mes de envío.</p>
`},
{t:"pl300", s:C2, h:`
<p><b>Contoso, Ltd.</b> (equipo para actividades al aire libre). Los analistas preparan a mano en Excel los informes trimestrales del consejo: cuenta de resultados de 4 unidades de negocio, balance y proyecciones del próximo trimestre.</p>
<p><b>Orígenes:</b> ingresos, costes y gastos en Azure SQL; balance resumido en Dynamics 365 Business Central (saldo final por cuenta y mes, siempre una fila por cuenta y mes); proyecciones mensuales en una lista de SharePoint Online (Projections) relacionadas por fecha, unidad de negocio, departamento y categoría. Ingresos a nivel de fecha y producto; gastos a nivel de fecha y departamento.</p>
<p><b>Problemas:</b> dos analistas una semana por trimestre, errores de referencias de celda y agrupaciones inconsistentes. <b>Objetivo:</b> automatizar con Power BI, menos de dos días, lógica común de unidades, productos y departamentos.</p>
<p><b>Técnicos:</b> mínimo esfuerzo manual, un único paquete de informes con navegación personalizada y enlaces. <b>Seguridad:</b> disponible en powerbi.com; grupo de seguridad habilitado para correo para el consejo; los analistas ven lo mismo que el consejo salvo la cuenta de resultados, limitada a su unidad; pueden crear informes nuevos con el modelo de resultados pero no se incluyen en el paquete; no pueden compartir los informes trimestrales.</p>
<p><b>Informes:</b> balance relacionado con la tabla de fechas (varios a uno) por el último día del mes; saldos finales del trimestre y del anterior; columna RevenueProjection; tendencias de ingresos, saldos finales, gastos frente a proyecciones, cambios en pasivos a largo plazo e ingresos trimestrales frente al mismo trimestre del año anterior.</p>
`},
{t:"pl300", s:C3, h:`
<p><b>Contoso, Ltd.</b> (equipo deportivo). Mismo planteamiento que el caso 2: balances y cuentas de resultados de 4 unidades de negocio preparados a mano en Excel. Balance con saldos finales mensuales por cuenta; catálogo de productos agrupados en categorías y unidades de negocio; ingresos por fecha y producto; gastos por fecha y departamento.</p>
<p><b>Seguridad:</b> grupo de Azure AD para el consejo; los analistas acceden a todo el balance y al catálogo, solo a la cuenta de resultados de su unidad, pueden crear informes nuevos con el modelo de resultados (fuera del paquete del consejo), no pueden compartir los informes trimestrales y <b>no pueden crear informes con los datos del balance</b>.</p>
<p><b>Informes:</b> balance relacionado con fechas por el último día del mes; saldos finales del trimestre y del anterior; tendencias de ingresos, saldos finales, cambios en deuda a largo plazo, % de ingresos por categoría e ingresos frente al mismo trimestre del año anterior. Actualización diaria a las 5:00.</p>
`}
);

EXAM.push(
{k:"Caso práctico", t:"calendario", s:C1, q:"Litware: columna calculada para mostrar el mes con formato «Feb 2020». A) FORMAT('Date'[date], \"MMM YYYY\") B) FORMAT('Date'[date], \"M YY\") C) FORMAT('Date'[date_id], \"MMM\") &amp; \"\" &amp; FORMAT('Date'[year], \"#\") D) FORMAT('Date'[date_id], \"MMM YYYY\")", a:"A. FORMAT sobre la columna de fecha real con \"MMM YYYY\". date_id es un número yyyymmdd, no una fecha."},
{k:"Caso práctico", t:"relaciones", s:C1, q:"Litware: ¿qué debes hacer antes de crear la relación para el visual de ventas por región de los ejecutivos?", a:"Cambiar el tipo de Sales[region_id] a Número entero para que coincida con la clave de la tabla de regiones (las columnas relacionadas deben tener el mismo tipo)."},
{k:"Caso práctico", t:"medidas", s:C1, q:"Litware: el departamento de ventas necesita informes con el número de transacciones. ¿Qué creas? A) medida SUM(Sales[sales_id]) B) columna COUNTA(Sales[sales_id]) C) medida COUNTROWS(Sales) D) columna SUM(Sales[sales_id])", a:"C. Una medida con COUNTROWS(Sales): cada fila es una transacción. Sumar ids no tiene sentido y una columna calculada no agrega."},
{k:"Caso práctico", t:"percepcion", s:C1, q:"Litware: visual para que los gerentes de ventas analicen el desempeño frente a los objetivos. ¿Cómo lo configuras?", a:"Tipo de visual KPI; Indicador: Sales[sales_amount]; Eje de tendencia: Date[month]; Objetivos: Target[sales_agent]."},
{k:"Caso práctico", t:"rls", s:C1, q:"Litware: los gerentes de ventas solo deben ver su región. ¿Qué incluyes en la solución?", a:"Un rol de seguridad con filtro de tabla en Sales_Manager donde username = USERNAME(). (En Service USERNAME devuelve el UPN, igual que USERPRINCIPALNAME.) No sirve comparar con ids ni con el nombre."},
{k:"Caso práctico", t:"relaciones", s:C1, q:"Litware: visual filtrable de forma independiente por mes de venta y mes de envío. ¿Qué relaciones creas?", a:"Una relación uno a varios de Date[date_id] a Sales[sales_date_id] y otra uno a varios de Date[date_id] a Sales[sales_ship_date_id] (una de ellas inactiva y activada con USERELATIONSHIP). Las opciones varios a varios o con la dirección invertida son incorrectas."},
{k:"Caso práctico", t:"medidas", s:C1, q:"Litware: para cumplir los requisitos del departamento de ventas sobre importes, ¿qué creas? (IF/ISBLANK en columna, SUMX(FILTER(... &gt; 0)), SUM en medida, ABS en columna)", a:"Una medida SUM(Sales[sales_amount]). Filtrar los negativos o usar ABS ocultaría el problema de calidad que se quiere detectar."},
{k:"Caso práctico", t:"rls", s:C1, q:"Litware: has combinado Sales_Region, Region_Manager, Sales_Manager y Manager en una tabla Region. ¿Qué haces a continuación?", a:"Aplicar seguridad a nivel de fila a la tabla Region basada en el nombre de usuario del gerente de ventas."},
{k:"Caso práctico", t:"roles", s:C2, q:"Contoso (aire libre): ¿qué configuras para dar acceso a los analistas de las unidades de negocio?", a:"Permisos de acceso de la aplicación y permiso de Compilación (Build) sobre el modelo: así pueden crear informes nuevos con el modelo de resultados sin modificar ni compartir los informes del consejo."},
{k:"Caso práctico", t:"roles", s:C2, q:"Contoso (aire libre): ¿cómo distribuyes los informes al consejo?", a:"Mediante una aplicación de Power BI publicada a un grupo de seguridad de Azure AD (habilitado para correo). La app da un paquete único con navegación personalizada y enlaces."},
{k:"Caso práctico", t:"dataflows", s:C2, q:"Contoso: estrategia para definir de forma consistente unidad de negocio, departamento y categoría de producto en todos los informes.", a:"Crear flujos de datos (dataflows) con los datos estandarizados y usarlos en todos los modelos importados. Un modelo compartido por entidad o exportar a Excel no garantizan la reutilización."},
{k:"Caso práctico", t:"rls", s:C2, q:"Contoso: una vez creado el modelo de pérdidas y ganancias, ¿qué cuatro acciones, en orden, aseguran que cada analista vea solo su unidad?", a:"1) En Desktop, crear 4 roles. 2) En Desktop, añadir a los roles una expresión DAX de filtro de tabla. 3) Publicar el modelo en powerbi.com. 4) En powerbi.com, agregar miembros a los roles."},
{k:"Caso práctico", t:"obtener", s:C2, q:"Contoso: ¿cuál es el número mínimo de modelos y modos de almacenamiento para los informes?", a:"Dos modelos importados: uno para la cuenta de resultados (con RLS y permiso de compilación) y otro para el balance."},
{k:"Caso práctico", t:"ti", s:C2, q:"Contoso: ¿qué expresión da los saldos finales en el balance? A) CALCULATE(SUM(BalanceSheet[BalanceAmount]), DATESQTD('Date'[Date])) B) CALCULATE(SUM(...), LASTDATE('Date'[Date])) C) FIRSTNONBLANK(...) D) CALCULATE(MAX(...), LASTDATE(...))", a:"Según el apunte, A (DATESQTD). Ojo: como el balance trae saldos de cierre mensuales y se relaciona por el último día de mes, muchas soluciones de la comunidad defienden B (LASTDATE), que devuelve el saldo al último día del periodo en lugar de sumar los meses del trimestre. Repasa el razonamiento de medidas semiaditivas."},
{k:"Caso práctico", t:"service", s:C3, q:"Contoso (deportes): los datos deben actualizarse a las 5:00 cada día con el mínimo esfuerzo. ¿Qué haces?", a:"Configurar una actualización programada sin puerta de enlace de datos local (los orígenes del caso están en la nube)."},
{k:"Caso práctico", t:"grupos", s:C3, q:"Contoso (deportes): los analistas deben poder explorar en profundidad rápidamente desde unidad de negocio hasta producto. ¿Qué creas?", a:"Una jerarquía (unidad de negocio &gt; categoría &gt; producto)."},
{k:"Caso práctico", t:"relaciones", s:C3, q:"Contoso (deportes): relación entre la lista de productos y los ingresos minimizando el tiempo de renderizado. ¿Qué cardinalidad?", a:"Uno a varios (de productos a ingresos), con filtro en una dirección."},
{k:"Visualización", t:"interactividad", s:S, q:"Informe con un gráfico de anillo y uno de columnas agrupadas (interacciones por defecto). Al seleccionar una columna, el anillo debe redibujarse con los datos de esa columna. ¿Qué haces?", a:"Seleccionar el gráfico de columnas (el origen de la selección) y, en Editar interacciones, poner la interacción con el anillo en Filtrar. Por defecto el anillo solo resalta."},
{k:"Service", t:"service", s:S, q:"Un modelo poco usado se actualiza cada hora y recibes aviso de que la actualización se desactivó por inactividad. ¿Qué dos acciones reanudan la programación?", a:"Abrir desde Power BI Service un panel que use el modelo o abrir un informe que lo use. Power BI pausa las actualizaciones de modelos sin visitas en dos meses."},
{k:"Seguridad", t:"rls", s:S, q:"Hay cuatro departamentos y cada usuario solo debe ver los datos del suyo. ¿Qué haces?", a:"Crear un rol RLS por departamento y definir la pertenencia de cada rol. Un segmentador o un parámetro no protegen los datos."},
{k:"Modelado", t:"relaciones", s:S, q:"Una columna «Plant Image» contiene URL de imágenes y la tabla muestra el texto de la URL. ¿Cómo muestras la imagen?", a:"Establecer la categoría de datos de la columna como URL de imagen (no URL web ni tipo binario)."},
{k:"Seguridad", t:"rls", s:S, q:"Debes pasar el mantenimiento de la pertenencia RLS a un equipo de seguridad de red de Azure sin darle capacidad de gestionar informes, modelos ni paneles.", a:"Según el apunte, A: dar permisos de lectura y compilación sobre los modelos. Muchas soluciones de la comunidad prefieren C: que el equipo cree y mantenga grupos de seguridad y configurar la RLS con esos grupos, de modo que gestionan la pertenencia sin tocar Power BI. Revísalo con la documentación."},
{k:"Power Query", t:"combinar", s:S, q:"Desnormalizar en una tabla Sales_Region (1:1 con Region_Manager), Region_Manager (cada registro existe en Manager, que tiene más), Sales_Manager (más registros que Sales_Region). Solo gerentes asociados a una región. ¿Qué tres combinaciones, en orden?", a:"1) Combinar Sales_Region y Sales_Manager con unión interna. 2) Combinar Region_Manager y Manager con unión interna. 3) Combinar Sales_Region y Region_Manager con unión externa derecha como nueva consulta Sales_Region_and_Region_Manager."},
{k:"Service", t:"service", s:S, q:"ReportA y ReportB usan paletas distintas; creas un panel con dos visuales de cada uno con tema oscuro coherente, preservando los colores originales. ¿Qué dos acciones?", a:"Seleccionar el tema oscuro para el panel y, al anclar los visuales, elegir «Usar el tema de destino»."},
{k:"Perfil de datos", t:"perfilado", s:S, q:"Debes analizar la distribución de frecuencias de la longitud del texto en col1 sin afectar al tamaño del modelo.", a:"En el Editor de Power Query, cambiar la distribución del perfil de columna para agrupar por longitud de texto. Añadir columnas (DAX o M) aumenta el modelo."}
);
})();
